### ISSUE TITLE
upload initial code

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/PNI_Trax#1]
please upload the initial code. let's keep this on track for being tracked on github

**Comment by sameer-vaze** [comment]
I've tested some code with termios as a way to interface with the IMU. The current test is based on a logger system that is running on a KL25Z across the UART routed through USB. Works like a charm. Will now move on to encapsulation and calibration for the PNI TRAX IMU using termios as an the terminal.

**Comment by sameer-vaze** [comment]
I've tested and uploaded to the repo some code that uses the termios package to interface with the system across the USB. The application used for testing right now is a logger system on the KL25Z board that sends data through the UART routed via USB. Will now move on to encapsulation and calibration for the PNI TRAX IMU. Will also include data structure or shared memory resource so that all data received from the IMU will be available for the ROS system.

**Comment by rishisoni10** [comment]
IMU raw data being printed
